### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by SlawekNowy**
Bulk of these will aprecciated by those using compressonator as submodule and using stricter compiler flags.

### CODE REVIEW

**Comment by NPCompress** [comment]
@SlawekNowy  Please review your latest pull request against v4.5 there are some conflicting files that need resolving. Thx

**Comment by SlawekNowy** [comment]
> @SlawekNowy Please review your latest pull request against v4.5 there are some conflicting files that need resolving. Thx

Done.

**Review by denislevesqueAMD — APPROVED** [review]
Looks good to me, thanks!

**Comment by denislevesqueAMD** [comment]
@NPCompress This can be merged

**Pull request merged**
