### PR TITLE
Feature/glm cleanup

### PR DESCRIPTION
**Pull request by UebelAndre**
This is the next pull request from #118 In order to avoid having Windows/DirectX headers included in common places, the use of `DirectXMath.h` has been replaced with GLM in occasion to support the already existing use of GLM in the Vulkan model viewer.

### CODE REVIEW

**Comment by UebelAndre** [comment]
Continuing the thread from #118 here:

> @UebelAndre PR accepted, However further merger is pending please wait for any additional PR until the master branch has been updated as commented prior following these steps.
> 
>     1. Removal of VS2015 folder in main folder
> 
>     2. Rename of VS2015 folders in sub folders
> 
>     3. Create VS2017 folder in main folder (Temporary until new CMake is provided)
> 
>     4. Updated environment vars to use user installed QTDIR & VULKAN_SDK
> 
>     5. Move sub folder Compressonator up to main folder
> 
>     6. Temporary rename Common folder to External (It will be removed and new build scripts will generate its contents)
> 
>     7. Add scripts to pull external libs (for now its a mixture of python and sub modules)
> 
>     8. Add Jenkins build scripts and documentation for user setup
> 
>     9. Definitions and documentation for unit and various other tests.
> 
> 
> This updates may take a few weeks as internal build systems are also going through a maintenance update


> @UebelAndre I see you have also added Feature/glm cleanup #119, Will also review this change. Please hold off on further PR until code has fully been merged with new changes and updates are completed. Thank you for your changes and continued support.

@NPCompress Hey! Sorry I didn't see your messages, got super excited when I saw the PR was merged and immediately opened the next one. I can make sure future PRs contain these changes. Do you guys have a branch/PR with the changes in them so I can stay up to date on when I should rebase?

**Comment by NPCompress** [comment]
@UebelAndre  Sorry we do not provide a branch for users to monitor development. We maintain internal development branches only.

**Comment by UebelAndre** [comment]
@NPCompress Ok, thanks. Do you know when the changes you mentioned would be merged?

**Comment by NPCompress** [comment]
@UebelAndre It will take a couple of weeks or less. Will notify you in this PR when its done.

**Comment by NPCompress** [comment]
@UebelAndre The code is now at step 7., however your PR has conflicts that need to be resolved. Can you look at them and issue a new PR. Note the common folder is removed, but will be replaced by a script that will pull all libs as needed by the project files. This update should be ready by end of the week.

**Comment by UebelAndre** [comment]
@NPCompress Hey! Sorry about the delay. And thanks for the update. I’ll see if I can get around to updating this PR sometime this weekend

**Comment by UebelAndre** [comment]
I believe this change should now be good to go again.

**Comment by NPCompress** [comment]
@UebelAndre  Sorry for the delay, Please remove submodules and replace with using build/fetch_dependencies.py,
Just add links  to the lines under downloadMappingWin & downloadMappingLin, some use samples are provided there for existing libs, you can use a specific archive branch of glm (for known stable builds) or pull from master.

"https://github.com/g-truc/glm.git" :  "../../Common/Lib/Ext/glm"

**Comment by NPCompress** [comment]
@UebelAndre I will be merging this code, after another push will be performed with some minor fixes to this merger along with other changes that are currently in progress.

**Pull request merged**
