### PR TITLE
cmake: Use proper way to find link OpenEXR, Thread and internal libraries on Unix.

### PR DESCRIPTION
**Pull request by lubosz**
These patches contain fixes for the CMake build system on Linux.

It applies are conventional way of retrieving dependencies as well as linking internal libraries.

Without this patch set I was unable to build Compressonator on Arch Linux. These patches should build on other Linux distros like Ubuntu and on macOS as well. Since everything in these patches is in the `if (UNIX)` branch, it shouldn't have any impact on the Windows build.

In addition to using the CMake target names and find_package, these patches use shorter syntax to append multiple elements to a list.

You can find details in the respective commit messages.

### CODE REVIEW

**Comment by Flakebi** [comment]
Hi @lubosz,
I do have a `OpenEXR.pc` on my system (though no `OpenEXRConfig.cmake`).
Using `pkg-config` is definitely nice, so lets screw my pull request.

The `target_include_directories(CompressonatorCLI-bin` lines in the wrong files were copy-paste errors, they should actually add the paths to the corresponding project.

Your PR works for me when I add `${OpenEXR_INCLUDE_DIRS}` to `Compressonator/Applications/_Plugins/CAnalysis/Analysis/CMakeLists.txt` and `Compressonator/Applications/_Plugins/CImage/EXR/CMakeLists.txt`.
([diff here](https://github.com/Flakebi/Compressonator/commit/0f442994226c6735bf6eaffec6c0edaf440595c9?w=1))

**Comment by lubosz** [comment]
@Flakebi Thanks a lot. I haven't seen the missing hard coded include paths! I will update my MR.

**Comment by Flakebi** [comment]
Thanks! It compiles fine now.

**Comment by NPCompress** [comment]
Resolved by GUI: Port to Qt5, implement CMake build, port to Linux, make Draco optional #87

**Pull request closed without merging**
