### PR TITLE
Removal of stdafx and targetver header files

### PR DESCRIPTION
**Pull request by UebelAndre**
Second pull request following #117 
This change removes the common file `stdafx.h` and places ensures that only the required headers are included where and when necessary. This was necessary in being able to isolate windows specific functionality in certain parts of the code and also increase clarity on where includes were coming from.

### CODE REVIEW

**Comment by UebelAndre** [comment]
@NPCompress Also, I hope these conversations are not distracting from the actual content of the pull request. Do you think it'd be better just to open a pull request for the `feature/cpp17` branch and continue the discussion there? It is the most interesting branch I have but I also have some other interesting changes on branches `feature/cpp17` is based on.

**Comment by NPCompress** [comment]
@UebelAndre  Let's focus on the existing pull request, can continue the discussion later for other pull requests.

**Comment by UebelAndre** [comment]
@NPCompress Sounds good. So what's the status of this pull request?

**Comment by NPCompress** [comment]
@UebelAndre still reviewing the source changes, once done it will go through  builds against our Jenkins servers, on successful  builds code will be merged.  Completed later today.

**Comment by UebelAndre** [comment]
@NPCompress I was wondering (just so I have some metrics to compare with for some of my changes) how long to builds for this project typically take? Would you be willing to share the specs of your Jenkins slaves?

**Comment by NPCompress** [comment]
@UebelAndre ,  For windows it takes less than 40 minutes to build full release packages (That's GUI, CLI and all SDK libs). For Linux CLI tar its under 4 minutes.

The development code is been updated and is moving to use VS2017 (currently removing VS2015, moving the common folder out and shifting compressonator/compressonator up one level), this will take some time and your pull request is also been merged in with the current code. I will post the Jenkins build specs once these changes are completed.

**Comment by UebelAndre** [comment]
@NPCompress hey, friendly poke. Any updates on the PR?

**Comment by NPCompress** [comment]
@UebelAndre PR accepted, However further merger is pending please wait for any additional PR until the master branch has been updated as commented prior following these steps.

1. Removal of VS2015 folder in main folder
2. Rename of VS2015 folders in sub folders
3. Create VS2017 folder in main folder (Temporary until new CMake is provided)
4. Updated environment vars to use user installed QTDIR & VULKAN_SDK
5. Move sub folder Compressonator up to main folder
6. Temporary rename Common folder to External (It will be removed and new build scripts will generate its contents)
7. Add scripts to pull external libs (for now its a mixture of python and sub modules)
8. Add Jenkins build scripts and documentation for user setup
9. Definitions and documentation for unit and various other tests.

This updates may take a few weeks as internal build systems are also going through a maintenance update

**Comment by NPCompress** [comment]
@UebelAndre I see you have also added Feature/glm cleanup #119, Will also review this change. Please hold off on further PR until code has fully been merged with new changes and updates are completed. Thank you for your changes and continued support.

**Pull request merged**
